---
version: '3.8'

services:
  sales_master_api:
    container_name: sales_master_api
    image: node:18.12.1-alpine
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'yarn install && yarn build && yarn migration:run && yarn dev'
    ports:
      - '4000:4000'
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      APP_PORT: ${APP_PORT}
      DB_POSTGRES_HOST: ${DB_POSTGRES_HOST}
      DB_POSTGRES_PORT: ${DB_POSTGRES_PORT}
      DB_POSTGRES_NAME: '${DB_POSTGRES_NAME}'
      DB_POSTGRES_USER: ${DB_POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    depends_on:
      - db
    links:
      - db
    networks:
      - prv-net

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  prv-net:
    driver: bridge